import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Nav
    home: 'Home',
    achievers: 'Achievers',
    interviews: 'Interviews',
    news: 'News',
    awards: 'Awards',
    about: 'About',
    contact: 'Contact',
    admin: 'Admin Portal',
    searchPlaceholder: 'Search achievers, news, awards...',
    mediaChannel: 'Media Channel',
    suggestAchiever: 'Suggest Achiever',
    login: 'Login',
    logout: 'Log Out',
    myDistrict: 'District',

    // Hero / Home
    heroBadge: 'Sri Lanka’s Premier National Achievers Media',
    heroTitlePrefix: 'Honoring Sri Lanka’s',
    heroTitleHighlight: 'Unsung Icons',
    heroTitleSuffix: '& National Achievers',
    heroDescription: 'Documenting remarkable journeys of courage, innovation, and service across Sri Lanka. Watch exclusive video interviews, read verified history, and celebrate real national heroes.',
    exploreAchievers: 'Explore Achievers',
    watchInterviews: 'Watch Interviews',
    statsAchievers: 'Documented Stories',
    statsAwards: 'Awards & Laureates',
    statsViews: 'Video Interviews',
    statsDistricts: 'Diaspora Countries',

    // Sections
    featuredTitle: 'Featured Achievers',
    featuredSubtitle: 'Remarkable people whose journeys shape industries and inspire generations.',
    viewAllAchievers: 'View All 500+ Achievers',
    interviewsTitle: 'Latest Interviews',
    interviewsSubtitle: 'In-depth conversations with Sri Lanka’s extraordinary achievers.',
    viewAllInterviews: 'View All Interviews',
    awardsTitle: 'Awards Spotlight',
    awardsSubtitle: 'Celebrating outstanding individuals nominated by the community.',
    viewAllAwards: 'View All Awards',
    latestNews: 'Latest News',
    latestNewsSubtitle: 'Local and international stories that matter to Sri Lanka.',
    allNews: 'All News',
    allCategories: 'All Categories',

    // How to Recommend
    communityPart: 'Community Participation',
    howToRecommendTitle: 'How to Recommend Achievers & Request Awards',
    howToRecommendSubtitle: 'Empowering citizens across every district of Sri Lanka to nominate unsung heroes and recommend leaders for national honors.',
    step1Title: 'Register or Sign In',
    step1Desc: 'Create a free PeopleFirst account and select your native Sri Lankan district or overseas region.',
    step2Title: 'Suggest an Achiever',
    step2Desc: 'Fill out the recommendation form detailing their achievements, category, and native district.',
    step3Title: 'Editorial Verification',
    step3Desc: 'Our editorial board verifies records, fact-checks history, and schedules a video interview.',
    step4Title: 'Biographical Honor',
    step4Desc: 'The achiever is published in our 3D Book roll of honor & nominated for PeopleFirst National Awards.',
    recommendNow: 'Recommend an Achiever Now',

    // CTA
    joinMovement: 'Join the Movement',
    ctaTitle: 'Know an Extraordinary Achiever?',
    ctaSubtitle: 'Help us celebrate Sri Lanka’s hidden heroes. Nominate someone whose story deserves to be told.',
    suggestButton: 'Suggest an Achiever',
    learnAboutUs: 'Learn About Us',

    // News Page
    newsHeaderTitle: 'News & Updates',
    newsHeaderSubtitle: 'Explore real-time Sri Lankan news stories, scientific breakthroughs, sports achievements, and cultural heritage milestones.',
    nationalWire: 'National & International Wire',
    searchNews: 'Search headlines, keywords, or topics...',
    dateFilter: 'Date',
    allDates: 'All Dates',
    past24h: 'Past 24 Hours',
    pastWeek: 'Past 7 Days',
    pastMonth: 'Past 30 Days',
    customRange: 'Custom Range...',
    sortBy: 'Sort',
    newestFirst: 'Newest (Date & Time)',
    oldestFirst: 'Oldest First',
    alphabetical: 'Headline (A–Z)',
    readMore: 'Read More',
    readStory: 'Read Full Story',
    resetFilters: 'Reset All Filters',
    noNewsFound: 'No news stories match your filters',
    previousPage: 'Previous Page',
    nextPage: 'Next Page',
    pageOf: 'Page',

    // News Detail
    back: 'Back',
    goBack: 'Go Back',
    shareStory: 'Share Story',
    readingHistory: 'Your Reading History',
    recentlyViewed: 'Recently viewed stories',
    relatedStories: 'Related Stories',
    allHeadlines: 'All Headlines',
    linkCopied: 'Link Copied',

    // Comments / Feedback
    publicFeedback: 'Public Feedback & Tributes',
    commentingAs: 'Commenting as',
    leaveFeedbackPrompt: 'Leave a tribute or feedback (Sign in required when posting)',
    feedbackPlaceholder: 'Share your appreciation or feedback for this achiever...',
    postTribute: 'Post Tribute',
    signInAndPost: 'Sign In & Post',
    tributeRecorded: '✓ Your tribute has been recorded on the biography manuscript!',
    commentSubtitle: 'Your feedback will be displayed publicly in the biography roll.',

    // Categories
    catAll: 'All',
    catLocal: 'Local',
    catInternational: 'International',
    catSports: 'Sports',
    catEducation: 'Education',
    catHealth: 'Health',
    catEnvironment: 'Environment',
    catArts: 'Arts',
    catHealthcareMedicine: 'Healthcare & Medicine',
    catEducationHeritage: 'Education & Heritage',
    catEngineeringTech: 'Engineering & Technology',
    catSocialImpact: 'Social Impact',
    catHumanitarian: 'Humanitarian Service',

    // Footer
    tagline: 'Sri Lanka’s premier platform for documenting, celebrating, and sharing the extraordinary achievements of everyday heroes.',
    motto: '"People First, Voice Always"',
    allRightsReserved: '© 2026 PeopleFirst Media Channel. All rights reserved.',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    madeWithLove: 'Made with ❤️ in Sri Lanka 🇱🇰',

    // About Page
    aboutHeroTitle: 'About',
    aboutHeroHighlight: 'PeopleFirst',
    aboutMotto: '"People First, Voice Always"',
    aboutDescription: 'PeopleFirst Media Channel is Sri Lanka\'s premier platform dedicated to discovering, documenting, and celebrating the extraordinary achievements of everyday Sri Lankans.',
    ourMission: 'Our Mission',
    ourVision: 'Our Vision',
    missionText: 'To create the most comprehensive, accessible, and authentic archive of Sri Lankan achievement — ensuring that every extraordinary story is preserved forever and shared with the world.',
    visionText: 'A Sri Lanka where every achiever\'s story is known, celebrated, and used to inspire the next generation — a nation that uplifts its own heroes and shares their light with the world.',
    coreValues: 'Our Core Values',
    whatWeStandFor: 'What We Stand For',
    ourJourney: 'Our Journey',
    timelineImpact: 'A Timeline of Impact',
    ourPeople: 'Our People',
    meetTheTeam: 'Meet the Team',
    truthFirst: 'Truth First',
    truthFirstDesc: 'Every story is verified against independent sources before publication. We never compromise on accuracy.',
    peopleFirstVal: 'People First',
    peopleFirstDesc: 'Our subjects are not statistics — they are human beings whose dignity and stories we honour with care.',
    inclusiveVoice: 'Inclusive Voice',
    inclusiveVoiceDesc: 'We document achievers from all communities, ethnicities, religions, and regions of Sri Lanka.',
    standardsExcellence: 'Standards of Excellence',
    standardsDesc: 'Editorial independence, rigorous fact-checking, and professional storytelling guide every production.',

    // Contact Page
    getInTouch: 'Get In Touch',
    contactTitle: 'Contact',
    contactUs: 'Us',
    contactDesc: 'Have a story to share? Want to collaborate? Reach out to the PeopleFirst team.',
    followUs: 'Follow Us',
    sendMessage: 'Send a Message',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    subject: 'Subject',
    message: 'Message',
    yourName: 'Your name',
    subjectPlaceholder: 'How can we help?',
    messagePlaceholder: 'Tell us your story, question, or collaboration idea...',
    sending: 'Sending...',
    sendMessageBtn: 'Send Message',
    messageSent: 'Message Sent!',
    messageSentDesc: 'Thank you! We\'ll get back to you within 48 hours.',
    sendAnother: 'Send Another Message',

    // Awards Page
    recognitionHonours: 'Recognition & Honours',
    awardsPageTitle: 'Awards &',
    laureates: 'Laureates',
    awardsPageDesc: 'Celebrating those who have earned the highest recognition for their extraordinary contributions.',
    searchAwards: 'Search awards or nominees...',
    awardWinners: '🏆 Award Winners',
    currentNominees: '⭐ Current Nominees',
    recommendNominee: 'Recommend an Award Nominee',
    recommendNomineeDesc: 'Know someone who deserves national recognition? Nominate them for a PeopleFirst Award. Our panel of independent experts will review all nominations.',
    suggestNominee: 'Suggest an Award Nominee',
    learnOurProcess: 'Learn About Our Process',

    // Interviews Page
    youtubeChannel: 'PeopleFirst YouTube Channel',
    videoInterviews: 'Video',
    interviewsHighlight: 'Interviews',
    interviewsPageDesc: 'In-depth conversations with extraordinary Sri Lankans. Click any interview from the list to play.',
    allInterviews: 'All Interviews',
    searchInterviews: 'Search interviews...',
    readFullBio: 'Read Full Biography',
    watchOnYoutube: 'Watch on YouTube',

    // Achievers Page
    verifiedRegistry: 'Verified National Registry',
    achieversArchive: 'Achievers',
    archiveHighlight: 'Archive',
    achieversPageDesc: 'Explore the extraordinary stories of Sri Lankan achievers across healthcare, technology, sports, arts, and community leadership.',
    searchAchievers: 'Search achievers by name, field, or achievement...',
    found: 'Found',
    achieversLabel: 'Achievers',
    selectAchiever: 'Select Achiever',
    clickToPreview: 'Click to preview',
    verifiedHistory: 'Verified History',
    readBookBio: 'Read Book Biography',
    recognized: 'Recognized',
    openFullBook: 'Open Full Book & Video Theater',
    keyLaurels: 'Key Landmark Laurels',
    noAchieversFound: 'No achievers found for',
    selectPrompt: 'Select an achiever from the list to view their story.',

    // Nominate Page
    communityNominations: 'Community Nominations',
    nominateAchiever: 'Nominate an',
    nominateHighlight: 'Achiever',
    nominatePageDesc: 'Help us discover and celebrate Sri Lanka\'s extraordinary people. Every nomination is reviewed by our editorial board.',
    nomineeInfo: 'Nominee Information',
    nomineeName: 'Full Name',
    nomineeLocation: 'Location / District',
    categoryField: 'Category / Field',
    selectCategory: 'Select a category...',
    descriptionAchievements: 'Description of Achievements',
    keyAchievements: 'Key Achievements (one per line)',
    mediaLinks: 'Media & Social Links',
    youtubeLink: 'YouTube Interview / Video Link',
    facebookLink: 'Facebook Profile / Page',
    yourInfo: 'Your Information',
    yourFullName: 'Your Full Name',
    phoneNumber: 'Phone Number',
    agreeText: 'I confirm that the information I\'ve provided is accurate to the best of my knowledge. I agree to PeopleFirst\'s Terms of Use and Privacy Policy.',
    submittingNomination: 'Submitting Nomination...',
    submitNomination: 'Submit Nomination',
    nominationSubmitted: 'Nomination Submitted!',
    nominationThankYou: 'Thank you for nominating',
    nominationReview: 'Our editorial team will review your submission and contact you within 7-10 working days.',
    submitAnother: 'Submit Another Nomination',
    minChars: 'Minimum 100 characters. Be specific and detailed.',

    // Hidden Heroes Page
    unsungHeroes: 'Unsung Heroes',
    hiddenHeroesTitle: 'Hidden',
    hiddenHeroesHighlight: 'Heroes',
    hiddenHeroesDesc: 'These extraordinary individuals have dedicated their lives to others — often without recognition or fame. Their stories deserve to be heard.',
    aboutHiddenHeroes: 'About Hidden Heroes',
    aboutHiddenDesc: 'This section features Sri Lankans whose contributions often go unrecognized by mainstream media. From village healers to demining experts, from grassroots educators to conservation warriors — these are the people who quietly change lives every day.',
    nominateHiddenHero: 'Nominate a Hidden Hero',
    hiddenHeroBadge: 'Hidden Hero',

    // AchieverDetail Page
    backToArchive: 'Back to Achievers Archive',
    achieverNotFound: 'Achiever Profile Not Found',
    interviewPlaylist: 'Interview Playlist',
    nowPlaying: 'Now Playing',
    biographyRoll: '📜 Interactive Biography Roll of Honor',
    turnPages: 'Turn the Pages of',
    history: 'History',
    playingVideo: '🎥 Playing Video Interview',
    highQualityAudio: 'High Quality Audio',
    watchFullVideo: 'Watch full video interviews and historical archives for',
    relatedIcons: 'and related icons.',
  },

  si: {
    // Nav
    home: 'මුල් පිටුව',
    achievers: 'ජයග්‍රාහකයින්',
    interviews: 'සම්මුඛ සාකච්ඡා',
    news: 'පුවත්',
    awards: 'සම්මාන',
    about: 'අප ගැන',
    contact: 'සම්බන්ධ වන්න',
    admin: 'පරිපාලක පුවරුව',
    searchPlaceholder: 'ජයග්‍රාහකයින්, පුවත්, සම්මාන සොයන්න...',
    mediaChannel: 'මාධ්‍ය නාලිකාව',
    suggestAchiever: 'ජයග්‍රාහකයෙකු යෝජනා කරන්න',
    login: 'ඇතුල් වන්න',
    logout: 'ඉවත් වන්න',
    myDistrict: 'දිස්ත්‍රික්කය',

    // Hero / Home
    heroBadge: 'ශ්‍රී ලංකාවේ ප්‍රමුඛතම ජාතික ජයග්‍රාහකයින්ගේ මාධ්‍ය නාලිකාව',
    heroTitlePrefix: 'ශ්‍රී ලංකාවේ',
    heroTitleHighlight: 'අභිමානවත් ජයග්‍රාහකයින්',
    heroTitleSuffix: 'උපහාරයට පාත්‍ර කිරීම',
    heroDescription: 'ශ්‍රී ලංකාව පුරා ධෛර්යය, නවෝත්පාදනය සහ සේවාව පිළිබඳ සුවිශේෂී ගමන් මඟ ලේඛනගත කිරීම. සුවිශේෂී වීඩියෝ සම්මුඛ සාකච්ඡා නරඹන්න, තහවුරු කළ ඉතිහාසය කියවන්න.',
    exploreAchievers: 'ජයග්‍රාහකයින් ගවේෂණය කරන්න',
    watchInterviews: 'සම්මුඛ සාකච්ඡා නරඹන්න',
    statsAchievers: 'ලේඛනගත කතාන්දර',
    statsAwards: 'සම්මාන සහ සම්මානලාභීන්',
    statsViews: 'වීඩියෝ සම්මුඛ සාකච්ඡා',
    statsDistricts: 'ඩයස්පෝරා රටවල්',

    // Sections
    featuredTitle: 'විශේෂාංගගත ජයග්‍රාහකයින්',
    featuredSubtitle: 'ක්ෂේත්‍රයන් පරිවර්තනය කරන සහ පරම්පරා ගණනාවකට ආදර්ශ සපයන විශිෂ්ට පුද්ගලයින්.',
    viewAllAchievers: 'සියලුම ජයග්‍රාහකයින් 500+ බලන්න',
    interviewsTitle: 'නවතම සම්මුඛ සාකච්ඡා',
    interviewsSubtitle: 'ශ්‍රී ලංකාවේ සුවිශේෂී ජයග්‍රාහකයින් සමඟ ගැඹුරු සාකච්ඡා.',
    viewAllInterviews: 'සියලුම සම්මුඛ සාකච්ඡා බලන්න',
    awardsTitle: 'සම්මාන විශේෂාංග',
    awardsSubtitle: 'සමාජය විසින් නිර්දේශ කරන ලද විශිෂ්ට පුද්ගලයින් ඇගයීම.',
    viewAllAwards: 'සියලුම සම්මාන බලන්න',
    latestNews: 'නවතම පුවත්',
    latestNewsSubtitle: 'ශ්‍රී ලංකාවට වැදගත් වන දේශීය හා ජාත්‍යන්තර පුවත්.',
    allNews: 'සියලුම පුවත්',
    allCategories: 'සියලුම වර්ගීකරණයන්',

    // How to Recommend
    communityPart: 'ප්‍රජා සහභාගීත්වය',
    howToRecommendTitle: 'ජයග්‍රාහකයින් නිර්දේශ කිරීම සහ සම්මාන ඉල්ලුම් කිරීම',
    howToRecommendSubtitle: 'ශ්‍රී ලංකාවේ සෑම දිස්ත්‍රික්කයකම පුරවැසියන්ට නොදන්නා වීරයන් නම් කිරීමට සහ ජාතික ගෞරව සඳහා නායකයින් නිර්දේශ කිරීමට බලගැන්වීම.',
    step1Title: 'ලියාපදිංචි වන්න හෝ ඇතුල් වන්න',
    step1Desc: 'නොමිලේ PeopleFirst ගිණුමක් සාදා ඔබගේ ශ්‍රී ලාංකික දිස්ත්‍රික්කය තෝරන්න.',
    step2Title: 'ජයග්‍රාහකයෙකු යෝජනා කරන්න',
    step2Desc: 'ඔවුන්ගේ ජයග්‍රහණ, කාණ්ඩය සහ උපන් දිස්ත්‍රික්කය විස්තර කරන පෝරමය පුරවන්න.',
    step3Title: 'කතෘ මණ්ඩල තහවුරු කිරීම',
    step3Desc: 'අපගේ මණ්ඩලය වාර්තා සත්‍යාපනය කර වීඩියෝ සම්මුඛ සාකච්ඡාවක් සැලසුම් කරයි.',
    step4Title: 'චරිතාපදාන උපහාරය',
    step4Desc: 'ජයග්‍රාහකයා 3D පොත් ලේඛනයේ ප්‍රකාශයට පත් කර සම්මාන සඳහා නම් කෙරේ.',
    recommendNow: 'දැන්ම ජයග්‍රාහකයෙකු නිර්දේශ කරන්න',

    // CTA
    joinMovement: 'අප සමඟ එක්වන්න',
    ctaTitle: 'සුවිශේෂී ජයග්‍රාහකයෙකු දන්නවාද?',
    ctaSubtitle: 'ශ්‍රී ලංකාවේ සැඟවුණු වීරයන් සැමරීමට අපට උදව් කරන්න.',
    suggestButton: 'ජයග්‍රාහකයෙකු යෝජනා කරන්න',
    learnAboutUs: 'අප ගැන දැනගන්න',

    // News Page
    newsHeaderTitle: 'පුවත් සහ යාවත්කාලීන',
    newsHeaderSubtitle: 'ශ්‍රී ලාංකික පුවත්, විද්‍යාත්මක සොයාගැනීම්, ක්‍රීඩා ජයග්‍රහණ සහ සංස්කෘතික උරුමයන් ගවේෂණය කරන්න.',
    nationalWire: 'ජාතික සහ ජාත්‍යන්තර පුවත් සේවය',
    searchNews: 'පුවත් සිරස්තල, මාතෘකා සොයන්න...',
    dateFilter: 'දිනය',
    allDates: 'සියලුම දින',
    past24h: 'පසුගිය පැය 24',
    pastWeek: 'පසුගිය දින 7',
    pastMonth: 'පසුගිය දින 30',
    customRange: 'අභිරුචි පරාසය...',
    sortBy: 'පිළිවෙල',
    newestFirst: 'අලුත්ම (දිනය සහ වේලාව)',
    oldestFirst: 'පැරණිතම පළමුව',
    alphabetical: 'සිරස්තලය (A–Z)',
    readMore: 'තව කියවන්න',
    readStory: 'සම්පූර්ණ කතාව කියවන්න',
    resetFilters: 'පෙරහන් යළි සකසන්න',
    noNewsFound: 'ගැලපෙන පුවත් කිසිවක් හමු නොවීය',
    previousPage: 'පෙර පිටුව',
    nextPage: 'මීළඟ පිටුව',
    pageOf: 'පිටුව',

    // News Detail
    back: 'ආපසු',
    goBack: 'ආපසු යන්න',
    shareStory: 'කතාව බෙදාගන්න',
    readingHistory: 'ඔබගේ කියවීමේ ඉතිහාසය',
    recentlyViewed: 'මෑතකදී කියවූ කතා',
    relatedStories: 'ආශ්‍රිත පුවත්',
    allHeadlines: 'සියලුම සිරස්තල',
    linkCopied: 'සබැඳිය පිටපත් කරන ලදී',

    // Comments / Feedback
    publicFeedback: 'මහජන ප්‍රතිපෝෂණ සහ උපහාර',
    commentingAs: 'අදහස් දක්වන්නේ',
    leaveFeedbackPrompt: 'උපහාරයක් හෝ අදහසක් දක්වන්න (ඇතුල් වීම අවශ්‍යයි)',
    feedbackPlaceholder: 'මෙම ජයග්‍රාහකයා සඳහා ඔබගේ ඇගයීම හෝ අදහස් දක්වන්න...',
    postTribute: 'උපහාරය පළ කරන්න',
    signInAndPost: 'ඇතුල් වී පළ කරන්න',
    tributeRecorded: '✓ ඔබගේ උපහාරය චරිතාපදාන ලේඛනයේ සටහන් විය!',
    commentSubtitle: 'ඔබගේ ප්‍රතිපෝෂණය චරිතාපදාන ලේඛනයේ ප්‍රසිද්ධියේ දිස්වනු ඇත.',

    // Categories
    catAll: 'සියල්ල',
    catLocal: 'දේශීය',
    catInternational: 'ජාත්‍යන්තර',
    catSports: 'ක්‍රීඩා',
    catEducation: 'අධ්‍යාපන',
    catHealth: 'සෞඛ්‍ය',
    catEnvironment: 'පරිසර',
    catArts: 'කලා',
    catHealthcareMedicine: 'සෞඛ්‍ය සහ වෛද්‍ය',
    catEducationHeritage: 'අධ්‍යාපනය සහ උරුමය',
    catEngineeringTech: 'ඉංජිනේරු සහ තාක්ෂණ',
    catSocialImpact: 'සමාජ සත්කාර',
    catHumanitarian: 'මානුෂීය සේවය',

    // Footer
    tagline: 'ශ්‍රී ලංකාවේ සැඟවුණු විරුවන්ගේ සුවිශේෂී ජයග්‍රහණ ලේඛනගත කිරීමට, සැමරීමට සහ බෙදාගැනීමට ප්‍රමුඛතම වේදිකාව.',
    motto: '"පළමුව ජනතාව, සැමවිටම හඬ"',
    allRightsReserved: '© 2026 PeopleFirst මාධ්‍ය නාලිකාව. සියලුම හිමිකම් ඇවිරිණි.',
    privacyPolicy: 'පෞද්ගලිකත්ව ප්‍රතිපත්තිය',
    termsOfUse: 'භාවිත නියමයන්',
    madeWithLove: 'ශ්‍රී ලංකාවේ ආදරයෙන් නිපදවන ලදී 🇱🇰',

    // About Page
    aboutHeroTitle: 'ගැන',
    aboutHeroHighlight: 'PeopleFirst',
    aboutMotto: '"පළමුව ජනතාව, සැමවිටම හඬ"',
    aboutDescription: 'PeopleFirst මාධ්‍ය නාලිකාව ශ්‍රී ලාංකීය සාමාන්‍ය ජනතාගේ සුවිශේෂී ජයග්‍රහණ සොයාගැනීම, ලේඛනගත කිරීම සහ සැමරීම සඳහා ශ්‍රී ලංකාවේ ප්‍රමුඛ වේදිකාවකි.',
    ourMission: 'අපගේ මෙහෙවර',
    ourVision: 'අපගේ දැක්ම',
    missionText: 'ශ්‍රී ලාංකීය ජයග්‍රහණයේ වඩාත් සම්පූර්ණ, ප්‍රවේශ සහිත සහ සත්‍යාපිත ලේඛනාගාරය නිර්මාණය කිරීම — සෑම සුවිශේෂී කතාවක්ම සදාකාලිකව සුරකිනු ලබන බව සහතික කිරීම.',
    visionText: 'සෑම ජයග්‍රාහකයෙකුගේ කතාවම දන්නා, සැමරෙන සහ ඊළඟ පරම්පරාව ආශ්‍රිත කිරීමට භාවිත කෙරෙන ශ්‍රී ලංකාවක්.',
    coreValues: 'අපගේ මූලික සාරධර්ම',
    whatWeStandFor: 'අපි නියෝජනය කරන්නේ කුමක්ද',
    ourJourney: 'අපගේ ගමන',
    timelineImpact: 'බලපෑමේ කාලරේඛාව',
    ourPeople: 'අපගේ ජනතාව',
    meetTheTeam: 'කණ්ඩායම හමුවෙන්න',
    truthFirst: 'සත්‍යය පළමුව',
    truthFirstDesc: 'සෑම කතාවක්ම ස්වාධීන මූලාශ්‍ර සමඟ සත්‍යාපනය කෙරේ. අපි නිරවද්‍යතාවය සඳහා කිසිවිටෙකත් සම්මුතිවාදී නොවෙමු.',
    peopleFirstVal: 'ජනතාව පළමු',
    peopleFirstDesc: 'අපගේ විෂයයන් සංඛ්‍යාලේඛන නොවේ — ඔවුහු ගෞරවයෙන් ගරු කරන ලද කතාන්දර ඇති මිනිසුන් වෙති.',
    inclusiveVoice: 'සමාවිෂ්ඨ හඬ',
    inclusiveVoiceDesc: 'ශ්‍රී ලංකාවේ සියලු ප්‍රජාවන්, ජාතීන්, ආගම් සහ කලාපවල ජයග්‍රාහකයින් ලේඛනගත කිරීම.',
    standardsExcellence: 'විශිෂ්ටත්ව ප්‍රමිතීන්',
    standardsDesc: 'කර්තෘ ස්වාධීනත්වය, දැඩි කරුණු පරීක්ෂාව සහ වෘත්තීය කතන්දර නිර්මාණය සෑම නිෂ්පාදනයකම මඟ පෙන්වයි.',

    // Contact Page
    getInTouch: 'සම්බන්ධ වන්න',
    contactTitle: 'සම්බන්ධ',
    contactUs: 'කරන්න',
    contactDesc: 'බෙදාගැනීමට කතාවක් තිබේද? සහයෝගීව කටයුතු කිරීමට කැමතිද? PeopleFirst කණ්ඩායමට ළඟා වන්න.',
    followUs: 'අපව අනුගමනය කරන්න',
    sendMessage: 'පණිවිඩයක් යවන්න',
    fullName: 'සම්පූර්ණ නම',
    emailAddress: 'විද්‍යුත් ලිපිනය',
    subject: 'විෂය',
    message: 'පණිවිඩය',
    yourName: 'ඔබගේ නම',
    subjectPlaceholder: 'අපට කෙසේ උදව් කළ හැකිද?',
    messagePlaceholder: 'ඔබගේ කතාව, ප්‍රශ්නය හෝ සහයෝගීතා අදහස දන්වන්න...',
    sending: 'යවමින්...',
    sendMessageBtn: 'පණිවිඩය යවන්න',
    messageSent: 'පණිවිඩය යවන ලදී!',
    messageSentDesc: 'ස්තූතියි! අපි ඔබව ය.ය. 48 ක් ඇතුළත ය.',
    sendAnother: 'තවත් පණිවිඩයක් යවන්න',

    // Awards Page
    recognitionHonours: 'සම්මාන සහ ගෞරව',
    awardsPageTitle: 'සම්මාන සහ',
    laureates: 'සම්මානලාභීන්',
    awardsPageDesc: 'ඔවුන්ගේ සුවිශේෂී දායකත්වය සඳහා ඉහළම සම්මාන දිනාගත් අය සැමරීම.',
    searchAwards: 'සම්මාන හෝ නිර්දේශිතයින් සොයන්න...',
    awardWinners: '🏆 සම්මාන ජයග්‍රාහකයින්',
    currentNominees: '⭐ වත්මන් නිර්දේශිතයින්',
    recommendNominee: 'සම්මාන නිර්දේශිතයෙකු නිර්දේශ කරන්න',
    recommendNomineeDesc: 'ජාතික සම්මානයකට සුදුසු කෙනෙකු දන්නවාද? PeopleFirst සම්මානය සඳහා ඔවුන් නම් කරන්න.',
    suggestNominee: 'සම්මාන නිර්දේශිතයෙකු යෝජනා කරන්න',
    learnOurProcess: 'අපගේ ක්‍රියාවලිය ගැන දැනගන්න',

    // Interviews Page
    youtubeChannel: 'PeopleFirst YouTube නාලිකාව',
    videoInterviews: 'වීඩියෝ',
    interviewsHighlight: 'සම්මුඛ සාකච්ඡා',
    interviewsPageDesc: 'සුවිශේෂී ශ්‍රී ලාංකීයයන් සමඟ ගැඹුරු සාකච්ඡා. ඕනෑම සම්මුඛ සාකච්ඡාවක් ක්ලික් කර ධාවනය කරන්න.',
    allInterviews: 'සියලුම සම්මුඛ සාකච්ඡා',
    searchInterviews: 'සම්මුඛ සාකච්ඡා සොයන්න...',
    readFullBio: 'සම්පූර්ණ චරිතාපදානය කියවන්න',
    watchOnYoutube: 'YouTube හි නරඹන්න',

    // Achievers Page
    verifiedRegistry: 'සත්‍යාපිත ජාතික ලේඛනාගාරය',
    achieversArchive: 'ජයග්‍රාහකයින්',
    archiveHighlight: 'ලේඛනාගාරය',
    achieversPageDesc: 'සෞඛ්‍ය සේවා, තාක්ෂණය, ක්‍රීඩා, කලා සහ ප්‍රජා නායකත්වය හරහා ශ්‍රී ලාංකීය ජයග්‍රාහකයින්ගේ සුවිශේෂී කතාන්දර ගවේෂණය කරන්න.',
    searchAchievers: 'ජයග්‍රාහකයින් නම, ක්ෂේත්‍රය හෝ ජයග්‍රහණය අනුව සොයන්න...',
    found: 'හමු වූ',
    achieversLabel: 'ජයග්‍රාහකයින්',
    selectAchiever: 'ජයග්‍රාහකයෙකු තෝරන්න',
    clickToPreview: 'දිස්වීමට ක්ලික් කරන්න',
    verifiedHistory: 'සත්‍යාපිත ඉතිහාසය',
    readBookBio: 'පොත් චරිතාපදානය කියවන්න',
    recognized: 'සම්මානිත',
    openFullBook: 'සම්පූර්ණ පොත සහ වීඩියෝ රඟහල විවෘත කරන්න',
    keyLaurels: 'ප්‍රධාන සන්ධිස්ථාන ජයග්‍රහණ',
    noAchieversFound: 'සඳහා ජයග්‍රාහකයෙකු හමු නොවීය',
    selectPrompt: 'කතාව දිස්වීමට ලැයිස්තුවෙන් ජයග්‍රාහකයෙකු තෝරන්න.',

    // Nominate Page
    communityNominations: 'ප්‍රජා නාමනාම',
    nominateAchiever: 'ජයග්‍රාහකයෙකු',
    nominateHighlight: 'නාමනා කරන්න',
    nominatePageDesc: 'ශ්‍රී ලංකාවේ සුවිශේෂී ජනතාව සොයාගැනීමට හා සැමරීමට අපට උදව් කරන්න. සෑම නාමනාමයක්ම කතෘ මණ්ඩලය විසින් සමාලෝචනය කෙරේ.',
    nomineeInfo: 'නිර්දේශිත තොරතුරු',
    nomineeName: 'සම්පූර්ණ නම',
    nomineeLocation: 'ස්ථානය / දිස්ත්‍රික්කය',
    categoryField: 'කාණ්ඩය / ක්ෂේත්‍රය',
    selectCategory: 'කාණ්ඩයක් තෝරන්න...',
    descriptionAchievements: 'ජයග්‍රහණ විස්තරය',
    keyAchievements: 'ප්‍රධාන ජයග්‍රහණ (රේඛාවකට එකක්)',
    mediaLinks: 'මාධ්‍ය සහ සමාජ සබැඳි',
    youtubeLink: 'YouTube සම්මුඛ සාකච්ඡා / වීඩියෝ සබැඳිය',
    facebookLink: 'Facebook පැතිකඩ / පිටුව',
    yourInfo: 'ඔබගේ තොරතුරු',
    yourFullName: 'ඔබගේ සම්පූර්ණ නම',
    phoneNumber: 'දුරකතන අංකය',
    agreeText: 'මා ලබාදී ඇති තොරතුරු නිවැරදි බව සහතික කරමි. PeopleFirst නියමයන් සහ ගොනු ප්‍රතිපත්තියට එකඟ වෙමි.',
    submittingNomination: 'නාමනාමය ඉදිරිපත් කරමින්...',
    submitNomination: 'නාමනාමය ඉදිරිපත් කරන්න',
    nominationSubmitted: 'නාමනාමය ඉදිරිපත් විය!',
    nominationThankYou: 'නාමනාමය කිරීම ගැන ස්තූතියි',
    nominationReview: 'අපගේ කතෘ මණ්ඩලය ඔබගේ ඉදිරිපත් කිරීම සමාලෝචනය කර කාර්‍ය දින 7-10 ක් ඇතුළත ඔබ සමඟ සම්බන්ධ වනු ඇත.',
    submitAnother: 'තවත් නාමනාමයක් ඉදිරිපත් කරන්න',
    minChars: 'අවම අකෂර 100. නිශ්චිත සහ විස්තරාත්මක වන්න.',

    // Hidden Heroes Page
    unsungHeroes: 'නොදන්නා වීරයින්',
    hiddenHeroesTitle: 'සැඟවුණු',
    hiddenHeroesHighlight: 'වීරයින්',
    hiddenHeroesDesc: 'මෙම සුවිශේෂී පුද්ගලයින් - බොහෝ විට සම්මාන හෝ කීර්තිය නොමැතිව - ඔවුන්ගේ ජීවිත අනෙකුත් අයට කැප කර ඇත. ඔවුන්ගේ කතාන්දර ඇසිය යුතුය.',
    aboutHiddenHeroes: 'සැඟවුණු වීරයින් ගැන',
    aboutHiddenDesc: 'මෙම කොටස ප්‍රධාන ධාරාවේ මාධ්‍ය විසින් බොහෝ විට නොදන්නා ශ්‍රී ලාංකීයයන්ගේ දායකත්ව ඉදිරිපත් කරයි.',
    nominateHiddenHero: 'සැඟවුණු වීරයෙකු නාමනා කරන්න',
    hiddenHeroBadge: 'සැඟවුණු වීරයා',

    // AchieverDetail Page
    backToArchive: 'ජයග්‍රාහකයින් ලේඛනාගාරයට ආපසු',
    achieverNotFound: 'ජයග්‍රාහක පැතිකඩ හමු නොවීය',
    interviewPlaylist: 'සම්මුඛ සාකච්ඡා ලැයිස්තුව',
    nowPlaying: 'දැන් ධාවනය',
    biographyRoll: '📜 අන්තර්ක්‍රියාකාරී චරිතාපදාන ශාඛාව',
    turnPages: 'ඉතිහාසයේ පිටු හරවන්න',
    history: 'ඉතිහාසය',
    playingVideo: '🎥 වීඩියෝ සම්මුඛ සාකච්ඡා ධාවනය',
    highQualityAudio: 'ඉහළ ගුණත්ව ශ්‍රව්‍ය',
    watchFullVideo: 'සඳහා සම්පූර්ණ වීඩියෝ සම්මුඛ සාකච්ඡා සහ ඓතිහාසික ලේඛනාගාර නරඹන්න',
    relatedIcons: 'සහ සම්බන්ධ ජයග්‍රාහකයින්.',
  },

  ta: {
    // Nav
    home: 'முகப்பு',
    achievers: 'சாதனையாளர்கள்',
    interviews: 'நேர்காணல்கள்',
    news: 'செய்திகள்',
    awards: 'விருதுகள்',
    about: 'எங்களைப் பற்றி',
    contact: 'தொடர்பு கொள்ள',
    admin: 'நிர்வாக மையம்',
    searchPlaceholder: 'சாதனையாளர்கள், செய்திகள், விருதுகளைத் தேடுங்கள்...',
    mediaChannel: 'ஊடக அலைவரிசை',
    suggestAchiever: 'சாதனையாளரைப் பரிந்துரைக்கவும்',
    login: 'உள்நுழைய',
    logout: 'வெளியேறு',
    myDistrict: 'மாவட்டம்',

    // Hero / Home
    heroBadge: 'இலங்கையின் முதன்மை தேசிய சாதனையாளர்கள் ஊடகம்',
    heroTitlePrefix: 'இலங்கையின்',
    heroTitleHighlight: 'புகழ்மிக்க சாதனையாளர்களை',
    heroTitleSuffix: 'கௌரவித்தல்',
    heroDescription: 'இலங்கை முழுவதும் தைரியம், புதுமை மற்றும் சேவையின் குறிப்பிடத்தக்க பயணங்களை ஆவணப்படுத்துதல். பிரத்யேக வீடியோ நேர்காணல்களைக் கண்டு, சரிபார்க்கப்பட்ட வரலாற்றைப் படியுங்கள்.',
    exploreAchievers: 'சாதனையாளர்களை ஆராயுங்கள்',
    watchInterviews: 'நேர்காணல்களைப் பாருங்கள்',
    statsAchievers: 'ஆவணப்படுத்தப்பட்ட கதைகள்',
    statsAwards: 'விருதுகள் மற்றும் வெற்றியாளர்கள்',
    statsViews: 'வீடியோ நேர்காணல்கள்',
    statsDistricts: 'புலம்பெயர் நாடுகள்',

    // Sections
    featuredTitle: 'சிறப்பு சாதனையாளர்கள்',
    featuredSubtitle: 'துறைகளை மாற்றியமைத்து தலைமுறைகளை ஊக்குவிக்கும் குறிப்பிடத்தக்க மனிதர்கள்.',
    viewAllAchievers: 'அனைத்து 500+ சாதனையாளர்களையும் காண்க',
    interviewsTitle: 'சமீபத்திய நேர்காணல்கள்',
    interviewsSubtitle: 'இலங்கையின் தலைசிறந்த சாதனையாளர்களுடன் ஆழமான உரையாடல்கள்.',
    viewAllInterviews: 'அனைத்து நேர்காணல்களையும் காண்க',
    awardsTitle: 'விருதுகள் சிறப்பு',
    awardsSubtitle: 'சமூகத்தால் பரிந்துரைக்கப்பட்ட சிறந்த நபர்களைக் கொண்டாடுதல்.',
    viewAllAwards: 'அனைத்து விருதுகளையும் காண்க',
    latestNews: 'சமீபத்திய செய்திகள்',
    latestNewsSubtitle: 'இலங்கைக்கு முக்கியத்துவம் வாய்ந்த உள்ளூர் மற்றும் சர்வதேச கதைகள்.',
    allNews: 'அனைத்து செய்திகள்',
    allCategories: 'அனைத்து பிரிவுகளும்',

    // How to Recommend
    communityPart: 'சமூகப் பங்கேற்பு',
    howToRecommendTitle: 'சாதனையாளர்களைப் பரிந்துரைப்பது மற்றும் விருதுகளைக் கோருவது எப்படி',
    howToRecommendSubtitle: 'இலங்கையின் ஒவ்வொரு மாவட்டத்திலும் உள்ள குடிமக்களுக்கு தகுதியானவர்களைப் பரிந்துரைக்க அதிகாரம் அளித்தல்.',
    step1Title: 'பதிவு செய்யுங்கள் அல்லது உள்நுழையவும்',
    step1Desc: 'இலவச PeopleFirst கணக்கை உருவாக்கி உங்கள் மாவட்டத்தைத் தேர்ந்தெடுக்கவும்.',
    step2Title: 'சாதனையாளரைப் பரிந்துரைக்கவும்',
    step2Desc: 'அவர்களின் சாதனைகள், பிரிவு மற்றும் மாவட்டத்தை விவரிக்கும் படிவத்தை நிரப்பவும்.',
    step3Title: 'ஆசிரியர் குழு சரிபார்ப்பு',
    step3Desc: 'எங்கள் குழு பதிவுகளைச் சரிபார்த்து வீடியோ நேர்காணலைத் திட்டமிடுகிறது.',
    step4Title: 'சுயசரிதை கௌரவம்',
    step4Desc: 'சாதனையாளர் 3D புத்தகத்தில் வெளியிடப்பட்டு விருதுகளுக்கு பரிந்துரைக்கப்படுகிறார்.',
    recommendNow: 'இப்போதே ஒரு சாதனையாளரைப் பரிந்துரைக்கவும்',

    // CTA
    joinMovement: 'எங்களுடன் இணையுங்கள்',
    ctaTitle: 'விசேட சாதனையாளர் ஒருவரைத் தெரியுமா?',
    ctaSubtitle: 'இலங்கையின் மறைக்கப்பட்ட கதாநாயகர்களைக் கொண்டாட எங்களுக்கு உதவுங்கள்.',
    suggestButton: 'சாதனையாளரைப் பரிந்துரைக்கவும்',
    learnAboutUs: 'எங்களைப் பற்றி அறியுங்கள்',

    // News Page
    newsHeaderTitle: 'செய்திகள் மற்றும் புதுப்பிப்புகள்',
    newsHeaderSubtitle: 'இலங்கை செய்திகள், அறிவியல் கண்டுபிடிப்புகள், விளையாட்டு சாதனைகள் மற்றும் கலாச்சார மைல்கற்களை ஆராயுங்கள்.',
    nationalWire: 'தேசிய மற்றும் சர்வதேச செய்திச் சேவை',
    searchNews: 'தலைப்புகள், முக்கிய சொற்களைத் தேடுங்கள்...',
    dateFilter: 'தேதி',
    allDates: 'அனைத்து தேதிகள்',
    past24h: 'கடந்த 24 மணிநேரம்',
    pastWeek: 'கடந்த 7 நாட்கள்',
    pastMonth: 'கடந்த 30 நாட்கள்',
    customRange: 'தனிப்பயன் வரம்பு...',
    sortBy: 'வரிசைப்படுத்து',
    newestFirst: 'புதியவை (தேதி மற்றும் நேரம்)',
    oldestFirst: 'பழையவை முதலில்',
    alphabetical: 'தலைப்பு (A–Z)',
    readMore: 'மேலும் படிக்க',
    readStory: 'முழு கதையையும் படிக்கவும்',
    resetFilters: 'வடிகட்டிகளை மீட்டமைக்கவும்',
    noNewsFound: 'வடிகட்டிகளுக்கு ஏற்ற செய்திகள் எதுவும் இல்லை',
    previousPage: 'முந்தைய பக்கம்',
    nextPage: 'அடுத்த பக்கம்',
    pageOf: 'பக்கம்',

    // News Detail
    back: 'பின்செல்க',
    goBack: 'பின்னுக்குச் செல்லவும்',
    shareStory: 'கதையைப் பகிரவும்',
    readingHistory: 'உங்கள் வாசிப்பு வரலாறு',
    recentlyViewed: 'சமீபத்தில் பார்த்த செய்திகள்',
    relatedStories: 'தொடர்புடைய செய்திகள்',
    allHeadlines: 'அனைத்து தலைப்புகளும்',
    linkCopied: 'இணைப்பு நகலெடுக்கப்பட்டது',

    // Comments / Feedback
    publicFeedback: 'பொதுமக்கள் கருத்துகள் & அஞ்சலி',
    commentingAs: 'கருத்து தெரிவிப்பவர்',
    leaveFeedbackPrompt: 'கருத்து தெரிவிக்க உள்நுழைய வேண்டும்',
    feedbackPlaceholder: 'இந்த சாதனையாளருக்கான உங்கள் பாராட்டைப் பகிர்ந்து கொள்ளுங்கள்...',
    postTribute: 'அஞ்சலியைப் பதிவு செய்க',
    signInAndPost: 'உள்நுழைந்து பதிவிடவும்',
    tributeRecorded: '✓ உங்கள் கருத்து சுயசரிதை ஆவணத்தில் பதிவு செய்யப்பட்டது!',
    commentSubtitle: 'உங்கள் கருத்து சுயசரிதை பதிவேட்டில் பகிரங்கமாகக் காட்டப்படும்.',

    // Categories
    catAll: 'அனைத்தும்',
    catLocal: 'உள்ளூர்',
    catInternational: 'சர்வதேசம்',
    catSports: 'விளையாட்டு',
    catEducation: 'கல்வி',
    catHealth: 'சுகாதாரம்',
    catEnvironment: 'சுற்றுச்சூழல்',
    catArts: 'கலை',
    catHealthcareMedicine: 'சுகாதாரம் மற்றும் மருத்துவம்',
    catEducationHeritage: 'கல்வி மற்றும் பாரம்பரியம்',
    catEngineeringTech: 'பொறியியல் மற்றும் தொழில்நுட்பம்',
    catSocialImpact: 'சமூக நலம்',
    catHumanitarian: 'மனிதநேய சேவை',

    // Footer
    tagline: 'இலங்கையின் சாதனையாளர்களின் சாதனைகளை ஆவணப்படுத்தவும், கொண்டாடவும் முதன்மையான தளம்.',
    motto: '"முதலில் மக்கள், எப்போதும் குரல்"',
    allRightsReserved: '© 2026 PeopleFirst ஊடக அலைவரிசை. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfUse: 'பயன்பாட்டு விதிமுறைகள்',
    madeWithLove: 'இலங்கையில் அன்புடன் உருவாக்கப்பட்டது 🇱🇰',

    // About Page
    aboutHeroTitle: 'பற்றி',
    aboutHeroHighlight: 'PeopleFirst',
    aboutMotto: '"முதலில் மக்கள், எப்போதும் குரல்"',
    aboutDescription: 'PeopleFirst ஊடக அலைவரிசை இலங்கையின் சாமான்ய மக்களின் அசாதாரண சாதனைகளை கண்டறிந்து, ஆவணப்படுத்தி, கொண்டாட முதன்மையான தளம்.',
    ourMission: 'எங்கள் நோக்கம்',
    ourVision: 'எங்கள் தொலைநோக்கு',
    missionText: 'இலங்கையின் சாதனைகளின் மிக விரிவான, அணுகக்கூடிய மற்றும் உண்மையான காப்பகத்தை உருவாக்குவது — ஒவ்வொரு அசாதாரண கதையும் என்றென்றும் பாதுகாக்கப்பட்டு உலகுடன் பகிரப்படுவதை உறுதி செய்வது.',
    visionText: 'ஒவ்வொரு சாதனையாளரின் கதையும் அறியப்பட்டு, கொண்டாடப்பட்டு, அடுத்த தலைமுறையை ஊக்குவிக்க பயன்படுத்தப்படும் இலங்கை.',
    coreValues: 'எங்கள் மூல மதிப்புகள்',
    whatWeStandFor: 'நாம் எதை நிலைநிறுத்துகிறோம்',
    ourJourney: 'எங்கள் பயணம்',
    timelineImpact: 'தாக்கத்தின் காலவரிசை',
    ourPeople: 'எங்கள் மக்கள்',
    meetTheTeam: 'குழுவை சந்தியுங்கள்',
    truthFirst: 'உண்மை முதலில்',
    truthFirstDesc: 'ஒவ்வொரு கதையும் வெளியிடுவதற்கு முன் சுயேச்சையான ஆதாரங்களுடன் சரிபார்க்கப்படுகிறது. நாங்கள் ஒருபோதும் துல்லியத்தில் சமரசம் செய்வதில்லை.',
    peopleFirstVal: 'மக்கள் முதலில்',
    peopleFirstDesc: 'எங்கள் விஷயங்கள் புள்ளிவிவரங்கள் அல்ல — அவர்கள் கவுரவத்துடன் மதிக்கப்படும் கதைகளைக் கொண்ட மனிதர்கள்.',
    inclusiveVoice: 'உள்ளடக்கிய குரல்',
    inclusiveVoiceDesc: 'இலங்கையின் அனைத்து சமூகங்கள், இனங்கள், மதங்கள் மற்றும் பகுதிகளிலிருந்து சாதனையாளர்களை ஆவணப்படுத்துகிறோம்.',
    standardsExcellence: 'சிறந்த தரநிலைகள்',
    standardsDesc: 'ஆசிரியர் சுதந்திரம், கடுமையான உண்மை சரிபார்ப்பு மற்றும் தொழில்முறை கதை சொல்லல் ஒவ்வொரு தயாரிப்பையும் வழிநடத்துகின்றன.',

    // Contact Page
    getInTouch: 'தொடர்பு கொள்ளுங்கள்',
    contactTitle: 'தொடர்பு',
    contactUs: 'கொள்ளுங்கள்',
    contactDesc: 'பகிர்வதற்கு கதை இருக்கிறதா? ஒத்துழைக்க விரும்புகிறீர்களா? PeopleFirst குழுவை அணுகுங்கள்.',
    followUs: 'எங்களை பின்தொடருங்கள்',
    sendMessage: 'செய்தி அனுப்புங்கள்',
    fullName: 'முழு பெயர்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    subject: 'விஷயம்',
    message: 'செய்தி',
    yourName: 'உங்கள் பெயர்',
    subjectPlaceholder: 'நாங்கள் எப்படி உதவலாம்?',
    messagePlaceholder: 'உங்கள் கதை, கேள்வி அல்லது ஒத்துழைப்பு யோசனையை சொல்லுங்கள்...',
    sending: 'அனுப்புகிறோம்...',
    sendMessageBtn: 'செய்தி அனுப்பு',
    messageSent: 'செய்தி அனுப்பப்பட்டது!',
    messageSentDesc: 'நன்றி! நாங்கள் 48 மணி நேரத்திற்குள் உங்களை தொடர்பு கொள்வோம்.',
    sendAnother: 'மற்றொரு செய்தி அனுப்பு',

    // Awards Page
    recognitionHonours: 'அங்கீகாரம் மற்றும் கௌரவங்கள்',
    awardsPageTitle: 'விருதுகள் மற்றும்',
    laureates: 'விருதுபெற்றவர்கள்',
    awardsPageDesc: 'தங்கள் அசாதாரண பங்களிப்புகளுக்கு மிக உயர்ந்த அங்கீகாரம் பெற்றவர்களை கொண்டாடுதல்.',
    searchAwards: 'விருதுகள் அல்லது பரிந்துரைக்கப்பட்டவர்களைத் தேடுங்கள்...',
    awardWinners: '🏆 விருது வெற்றியாளர்கள்',
    currentNominees: '⭐ தற்போதைய பரிந்துரைக்கப்பட்டவர்கள்',
    recommendNominee: 'விருது பரிந்துரை செய்யுங்கள்',
    recommendNomineeDesc: 'தேசிய அங்கீகாரத்திற்கு தகுதியானவரை தெரியுமா? PeopleFirst விருதுக்கு அவர்களை பரிந்துரையுங்கள்.',
    suggestNominee: 'விருது பரிந்துரையை பரிந்துரைக்கவும்',
    learnOurProcess: 'எங்கள் செயல்முறையை அறியுங்கள்',

    // Interviews Page
    youtubeChannel: 'PeopleFirst YouTube அலைவரிசை',
    videoInterviews: 'வீடியோ',
    interviewsHighlight: 'நேர்காணல்கள்',
    interviewsPageDesc: 'அசாதாரண இலங்கையர்களுடன் ஆழமான உரையாடல்கள். எந்த நேர்காணலிலும் கிளிக் செய்து இயக்கவும்.',
    allInterviews: 'அனைத்து நேர்காணல்கள்',
    searchInterviews: 'நேர்காணல்களைத் தேடுங்கள்...',
    readFullBio: 'முழு சுயசரிதையைப் படிக்கவும்',
    watchOnYoutube: 'YouTube இல் பாருங்கள்',

    // Achievers Page
    verifiedRegistry: 'சரிபார்க்கப்பட்ட தேசிய பதிவேடு',
    achieversArchive: 'சாதனையாளர்கள்',
    archiveHighlight: 'காப்பகம்',
    achieversPageDesc: 'சுகாதாரம், தொழில்நுட்பம், விளையாட்டு, கலை மற்றும் சமூக தலைமை ஆகியவற்றில் இலங்கை சாதனையாளர்களின் அசாதாரண கதைகளை ஆராயுங்கள்.',
    searchAchievers: 'சாதனையாளர்களை பெயர், துறை அல்லது சாதனையால் தேடுங்கள்...',
    found: 'கண்டுபிடிக்கப்பட்டது',
    achieversLabel: 'சாதனையாளர்கள்',
    selectAchiever: 'சாதனையாளரை தேர்ந்தெடுங்கள்',
    clickToPreview: 'முன்னோட்டத்திற்கு கிளிக் செய்யவும்',
    verifiedHistory: 'சரிபார்க்கப்பட்ட வரலாறு',
    readBookBio: 'புத்தக சுயசரிதையைப் படிக்கவும்',
    recognized: 'அங்கீகரிக்கப்பட்டது',
    openFullBook: 'முழு புத்தகம் மற்றும் வீடியோ திரையரங்கை திறக்கவும்',
    keyLaurels: 'முக்கிய மைல்கற்கள்',
    noAchieversFound: 'க்கான சாதனையாளர்கள் எதுவும் இல்லை',
    selectPrompt: 'கதையை பார்க்க பட்டியலிலிருந்து சாதனையாளரை தேர்ந்தெடுக்கவும்.',

    // Nominate Page
    communityNominations: 'சமூக பரிந்துரைகள்',
    nominateAchiever: 'ஒரு சாதனையாளரை',
    nominateHighlight: 'பரிந்துரைக்கவும்',
    nominatePageDesc: 'இலங்கையின் அசாதாரண மக்களை கண்டறிந்து கொண்டாட எங்களுக்கு உதவுங்கள். ஒவ்வொரு பரிந்துரையும் ஆசிரியர் குழுவால் மதிப்பாய்வு செய்யப்படுகிறது.',
    nomineeInfo: 'பரிந்துரைக்கப்பட்டவர் தகவல்',
    nomineeName: 'முழு பெயர்',
    nomineeLocation: 'இடம் / மாவட்டம்',
    categoryField: 'பிரிவு / துறை',
    selectCategory: 'ஒரு பிரிவை தேர்ந்தெடுக்கவும்...',
    descriptionAchievements: 'சாதனைகளின் விளக்கம்',
    keyAchievements: 'முக்கிய சாதனைகள் (வரிக்கு ஒன்று)',
    mediaLinks: 'ஊடக மற்றும் சமூக இணைப்புகள்',
    youtubeLink: 'YouTube நேர்காணல் / வீடியோ இணைப்பு',
    facebookLink: 'Facebook சுயவிவரம் / பக்கம்',
    yourInfo: 'உங்கள் தகவல்',
    yourFullName: 'உங்கள் முழு பெயர்',
    phoneNumber: 'தொலைபேசி எண்',
    agreeText: 'நான் வழங்கிய தகவல்கள் சரியானவை என்று உறுதிப்படுத்துகிறேன். PeopleFirst பயன்பாட்டு விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஒப்புக்கொள்கிறேன்.',
    submittingNomination: 'பரிந்துரையை சமர்பிக்கிறோம்...',
    submitNomination: 'பரிந்துரையை சமர்பிக்கவும்',
    nominationSubmitted: 'பரிந்துரை சமர்பிக்கப்பட்டது!',
    nominationThankYou: 'பரிந்துரைத்தமைக்கு நன்றி',
    nominationReview: 'எங்கள் ஆசிரியர் குழு உங்கள் சமர்பிப்பை மதிப்பாய்வு செய்து 7-10 வேலை நாட்களுக்குள் உங்களை தொடர்பு கொள்வார்கள்.',
    submitAnother: 'மற்றொரு பரிந்துரையை சமர்பிக்கவும்',
    minChars: 'குறைந்தது 100 எழுத்துக்கள். குறிப்பிட்டதாகவும் விரிவாகவும் இருங்கள்.',

    // Hidden Heroes Page
    unsungHeroes: 'அறியப்படாத கதாநாயகர்கள்',
    hiddenHeroesTitle: 'மறைக்கப்பட்ட',
    hiddenHeroesHighlight: 'கதாநாயகர்கள்',
    hiddenHeroesDesc: 'இந்த அசாதாரண நபர்கள் - பெரும்பாலும் அங்கீகாரம் அல்லது புகழ் இல்லாமல் - தங்கள் வாழ்க்கையை மற்றவர்களுக்காக அர்ப்பணித்துள்ளனர். அவர்களின் கதைகள் கேட்கப்பட வேண்டும்.',
    aboutHiddenHeroes: 'மறைக்கப்பட்ட கதாநாயகர்களைப் பற்றி',
    aboutHiddenDesc: 'இந்த பகுதி முக்கிய ஊடகங்களால் பெரும்பாலும் அங்கீகரிக்கப்படாத இலங்கையர்களின் பங்களிப்புகளை சிறப்பிக்கிறது.',
    nominateHiddenHero: 'மறைக்கப்பட்ட கதாநாயகரை பரிந்துரைக்கவும்',
    hiddenHeroBadge: 'மறைக்கப்பட்ட கதாநாயகர்',

    // AchieverDetail Page
    backToArchive: 'சாதனையாளர்கள் காப்பகத்திற்கு திரும்பு',
    achieverNotFound: 'சாதனையாளர் சுயவிவரம் கிடைக்கவில்லை',
    interviewPlaylist: 'நேர்காணல் தொகுப்பு',
    nowPlaying: 'இப்போது இயங்குகிறது',
    biographyRoll: '📜 ஊடாடும் சுயசரிதை கௌரவ சுருள்',
    turnPages: 'வரலாற்றின் பக்கங்களை திருப்புங்கள்',
    history: 'வரலாறு',
    playingVideo: '🎥 வீடியோ நேர்காணல் இயங்குகிறது',
    highQualityAudio: 'உயர் தர ஒலி',
    watchFullVideo: 'க்கான முழு வீடியோ நேர்காணல்களை பாருங்கள்',
    relatedIcons: 'மற்றும் தொடர்புடைய கதாநாயகர்கள்.',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      return localStorage.getItem('peoplefirst_lang') || 'en';
    } catch {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('peoplefirst_lang', lang);
      document.documentElement.lang = lang;
    } catch (e) {
      console.error(e);
    }
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
    }
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
